project:
  type: website
  output-dir: docs

website:
  title: "Satish Bajracharya"
  favicon: "img/person.svg"
  page-footer:
    center: |
      [Contact Satish Bajracharya](mailto:vajrasatis@gmail.com)
    left: |
      Made with [Posit Quarto](https://quarto.org/) in R
    right: |
      [Github Code Repo](https://github.com/vajra-satish/vajra-satish.github.io)
    background: "#2c3e50"
  search: 
   location: navbar
   type: overlay
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Data Analytics     
      href: data analytics.qmd
    - text: Blogs     
      href: blogs.qmd
    - text: Publications     
      href: publications.qmd
    - text: CV     
      href: cv.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/vajrasatis
format:
  html:
    theme: flatly
    css: styles.css
    code-link: true
    code-block-bg: true
    code-block-border-left: "#2c3e50"


